name: Lint with Ruff

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - '*.png'
      - '*.svg'
      - '.gitignore'
      - 'images/**'
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - '*.md'
      - '*.png'
      - '*.svg'
      - '.gitignore'
      - 'images/**'

jobs:
  ruff:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github
          src
          pyproject.toml
          requirements.txt

    - name: Lint with `ruff check .`
      uses: chartboost/ruff-action@v1